version: '3.8'
services:
  app:
    image: php:8.0-apache
    container_name: laravel-app
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8000:8000
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel: